/** Two-word couch wait copy for the Detail play button. Ellipsis is display-only. */

export const PLAY_WAIT_ROTATE_MS = 2500;
export const PLAY_WAIT_MAX_CHARS = 16;
export const PLAY_WAIT_ELLIPSIS = "…";

export const PLAY_WAIT_PHRASES: readonly string[] = [
  "dimming lights",
  "warming popcorn",
  "hushing crowd",
  "cueing overture",
  "folding blankets",
  "fluffing pillows",
  "lighting candles",
  "drawing drapes",
  "pouring fizz",
  "icing glasses",
  "buttering corn",
  "salting snacks",
  "waking lamp",
  "oiling reels",
  "threading film",
  "dusting seats",
  "ushering in",
  "closing doors",
  "muting phones",
  "dimming foyer",
  "raising curtain",
  "lowering boom",
  "cueing sound",
  "warming tubes",
  "coaxing picture",
  "summoning plot",
  "assembling cast",
  "hiding spoilers",
  "bribing ushers",
  "tipping popcorn",
  "finding seats",
  "saving aisle",
  "stretching legs",
  "parking dragons",
  "waking dragon",
  "oiling hinges",
  "winding clock",
  "striking match",
  "cueing fanfare",
  "polishing lens",
  "focusing beam",
  "aligning stars",
  "charging wand",
  "mixing potions",
  "opening portal",
  "unfolding map",
  "lighting fuse",
  "counting down",
  "holding breath",
  "hoping hard",
  "knocking wood",
  "spinning globe",
  "shaking globe",
  "brewing tea",
  "steeping cocoa",
  "warming cocoa",
  "toasting mallows",
  "fluffing cats",
  "tucking dogs",
  "bribing cats",
  "hushing dogs",
  "closing fridge",
  "hiding remotes",
  "herding cats",
  "summoning vibes",
  "plotting chaos",
  "hatching scheme",
  "warming engines",
  "revving plot",
  "fueling drama",
  "staging scene",
  "calling action",
  "rolling camera",
  "clapping slate",
  "marking scene",
  "quiet please",
  "hushing set",
  "placing boom",
  "painting sky",
  "hanging moon",
  "stacking clouds",
  "cueing thunder",
  "bottling sparks",
  "catching stars",
  "folding time",
  "stretching dusk",
  "inviting night",
  "unwrapping dusk",
  "rolling wrists",
  "tying cape",
  "donning cape",
  "polishing boots",
  "saddling horse",
  "waking kraken",
  "baiting hook",
  "casting spell",
  "shuffling cards",
  "dealing hands",
  "stacking odds",
  "rattling dice",
  "shaking dice",
  "warming bench",
  "stretching plot",
  "thickening plot",
  "salting story",
  "plating scene",
  "plating night",
  "pouring rain",
  "stirring mist",
  "brewing storm",
  "summoning fog",
  "unlocking vault",
  "cracking safe",
  "oiling plot",
  "winding plot",
  "cueing magic",
  "sprinkling dust",
  "tossing glitter",
  "tying balloons",
  "popping corn",
  "melting butter",
  "salting kettle",
  "icing soda",
  "chilling fizz",
  "chilling cups",
  "lining seats",
  "warming sofa",
  "claiming couch",
  "fortifying nest",
  "building fort",
  "piling pillows",
  "dimming hallway",
  "latching doors",
  "hushing kettle",
  "pausing world",
  "borrowing time",
  "cueing hush",
  "holding hush",
  "inviting hush",
  "waking screen",
  "polishing glass",
  "wiping lens",
  "cueing glow",
  "kindling glow",
  "fanning flames",
  "stoking fire",
  "laying fire",
  "stacking logs",
  "pouring syrup",
  "flipping pages",
  "cracking book",
  "opening book",
  "dimming study",
  "cueing titles",
  "rolling titles",
  "hushing lobby",
  "warming lobby",
  "seating guests",
  "handing tickets",
  "tearing stubs",
  "folding tickets",
  "checking coats",
  "hanging coats",
  "polishing brass",
  "tying bowtie",
  "shining shoes",
  "dusting marquee",
  "lighting sign",
  "raising sign",
  "unfurling flag",
  "striking pose",
  "clearing throat",
  "tapping baton",
  "lifting baton",
  "cueing choir",
  "warming choir",
  "hushing pit",
  "tuning strings",
  "rosining bow",
  "settling in",
  "scooching over",
  "claiming blanket",
  "stealing blanket",
  "sharing popcorn",
  "passing snacks",
  "opening snacks",
  "crinkling bags",
  "kicking shoes",
  "tucking feet",
  "curling up",
  "nesting in",
  "dimming world",
  "inviting dark",
  "courting dark",
  "greeting night",
  "unboxing night",
  "untying plot",
  "unspooling tape",
  "weaving dreams",
  "spinning yarn",
  "telling tales",
  "priming magic",
  "charging magic",
  "rubbing lamp",
  "wishing hard",
  "crossing paths",
  "opening gates",
  "lowering bridge",
  "raising gate",
  "oiling gate",
  "waking castle",
  "lighting lamps",
  "hanging lamps",
  "stirring pot",
  "bubbling pot",
  "tasting stew",
  "setting table",
  "folding napkins",
  "pouring juice",
  "slicing cake",
  "lighting cake",
  "hiding cake",
  "sneaking bites",
  "saving dessert",
  "warming pie",
  "cooling pie",
  "scooping ice",
  "shaking cream",
  "whipping cream",
  "melting ice",
  "frosting cake",
  "plating dessert",
  "ringing bell",
  "hushing bell",
  "cueing bell",
  "opening night",
  "encore please",
  "taking bow",
  "clearing stage",
  "setting stage",
  "dressing stage",
  "aiming light",
  "chasing light",
  "dimming house",
  "warming house",
  "hushing house",
  "sealing house",
  "pausing clocks",
  "spinning clocks",
  "winding watches",
  "oiling gears",
  "waking gears",
  "humming along",
  "tapping toes",
  "drumming fingers",
  "holding popcorn",
  "guarding snacks",
  "hiding snacks",
  "sneaking candy",
  "unwrapping gum",
  "popping candy",
  "chewing quietly",
  "breathing out",
  "settling pulse",
  "slowing pulse",
  "calming room",
  "softening room",
  "warming room",
  "darkening room",
  "hushing room",
  "readying room",
  "lighting wicks",
  "claiming quilt",
  "stealing quilt",
  "tucking quilt",
  "fluffing quilt",
  "warming socks",
  "parking shoes",
  "hiding shoes",
  "finding socks",
  "matching socks",
  "hanging stars",
  "pinning stars",
  "counting stars",
  "naming stars",
  "borrowing moon",
  "polishing moon",
  "waking sun",
  "tucking sun",
  "folding day",
  "stretching eve",
  "inviting eve",
  "feeding gremlins",
  "crossing fingers",
];

export function formatPlayWaitLabel(phrase: string): string {
  return `${phrase}${PLAY_WAIT_ELLIPSIS}`;
}

function shuffled<T>(items: readonly T[]): T[] {
  const next = items.slice();
  for (let i = next.length - 1; i > 0; i -= 1) {
    const j = Math.floor(Math.random() * (i + 1));
    const left = next[i];
    const right = next[j];
    if (left === undefined || right === undefined) {
      continue;
    }
    next[i] = right;
    next[j] = left;
  }
  return next;
}

export class PlayWaitCopy {
  private bag: string[] = [];
  private last: string | null = null;

  next(): string {
    return formatPlayWaitLabel(this.nextPhrase());
  }

  nextPhrase(): string {
    if (this.bag.length === 0) {
      this.refill();
    }
    const phrase = this.bag.pop();
    if (!phrase) {
      this.refill();
      return this.nextPhrase();
    }
    this.last = phrase;
    return phrase;
  }

  private refill(): void {
    const next = shuffled(PLAY_WAIT_PHRASES);
    if (this.last !== null && next.length > 1 && next[next.length - 1] === this.last) {
      const lastIndex = next.length - 1;
      const swapWith = Math.floor(Math.random() * (next.length - 1));
      const a = next[lastIndex];
      const b = next[swapWith];
      if (a !== undefined && b !== undefined) {
        next[lastIndex] = b;
        next[swapWith] = a;
      }
    }
    this.bag = next;
  }
}
